

spring.application.name=order-service
server.port=8082

spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Where product-service lives (hard-coded for now, we fix this in Project 2)
product-service.url=http://product-service

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true

server.error.include-message=always

management.tracing.sampling.probability=1.0
spring.cloud.circuitbreaker.resilience4j.disable-time-limiter=true

logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
